############### 下面的配置一般不用动 #######################################################
mybatis-plus:
  typeEnumsPackage: com.boot.**.enums
  global-config.banner: false

spring.datasource.driver-class-name: com.p6spy.engine.spy.P6SpyDriver

spring.jpa:
  hibernate:
    ddl-auto: update
    naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy # 遇到大写加_
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  #不加这句则默认为myisam
