site:
  explanation: 轨道机器人-测试环境
  host: http://47.97.223.112:60800/
  file-upload-dir: /data/java/file


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:33066/InspectionRobot?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

spring.resources.static-locations: file:/data/java