#项目名等配置
spring.application.name: InspectionRobot
site:
  app-name: ${spring.application.name}
  explanation: 轨道机器人
  file-upload-dir: /data/file

server:
  port: ${port:60800}
#  servlet.context-path: /api
