site:
  explanation: 轨道机器人-本地开发环境
  host: http://localhost:${server.port}/
  file-upload-dir: /Users/xinan/tmp/file

spring:
  datasource:
    url: jdbc:p6spy:mysql://47.97.223.112:33066/InspectionRobot?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
  redis:
    database: 0
    host: 47.97.223.112
    port: 6379
    password: 123456

spring.resources.static-locations: file:/Users/xinan/tmp
